### ISSUE TITLE
Doesnt work on Windows 8 x64

### ISSUE THREAD

**Issue by Rourke101** [secrary/InjectProc#2]
I have tried to reproduce the steps in the Youtube video and none works. For example, dll_inj says "Injected successfully" printed in the console (not in a window) but the DLL is not in the process...

**Comment by Kiina** [comment]
Do you have the DLL in your folder? I noticed it gives a success message in cmd if the DLL is missing. And it's the mbox.dll which is calling the Messagebox so without it you don't get the Window.

https://github.com/secrary/InjectProc/blob/master/InjectProc/test_files/mbox.dll

**Comment by Rourke101** [comment]
Yes, the DLL is in the same folder as the program, and it doesn't work:

C:\Users\tester\Desktop\injection
λ InjectProc.exe dll_inj myvirus.dll mspaint.exe
Injected Successfully

Afterwards, ProcessExplorer doesn't show the DLL in the mspaint.exe process.

With mbox.dll I get a "Bad Image" error: mbox.dll is either not designed to run on Windows or it contains an error.... Error status: -0xc000012f. But the program equally says "Injected Successfully".

I have tried with different DLLs with equal success. I am using a Windows 8 x64. The executable was compiled for x64 (couldn't make it work for x86 without getting involved with the code)
